# HOW TO DEPLOY, GET THE SECRETS AND IDs (to save on GitHub)
# Deploying Your Vercel Application with GitHub Actions:
# https://vercel.com/guides/how-can-i-use-github-actions-with-vercel

# APP: https://git-actions-to-vercel.vercel.app/

name: Vercel Deployment
on:
  workflow_run:
    workflows: ["Pull Request Test and Lint"]
    types:
      - completed
# on:
#   push:
#     branches:
#       - main

# env:
#   VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
#   VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

jobs:
  Deploy-Production:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
